// helpers/setup/examples/view-preact/src/index.tsx
import { meiosisSetup } from 'meiosis-setup';
import { MeiosisCell, MeiosisViewComponent } from 'meiosis-setup/types';
import preact from 'preact';

interface State {
  value: number;
}

const actions = {
  increment: (cell: MeiosisCell<State>, amount: number) =>
    cell.update({ value: (x) => x + amount })
};

const app: MeiosisViewComponent<State> = {
  initial: {
    value: 22
  },
  view: (cell) =>
    <div>
      <div>Temperature: {cell.state.value}&deg;C</div>
      <div>
        <button
          className="btn btn-primary btn-sm"
          onClick={() => actions.increment(cell, 1)}>
          Increment
        </button>
        <button
          className="btn btn-primary btn-sm ms-1"
          onClick={() => actions.increment(cell, -1)}>
          Decrement
        </button>
      </div>
    </div>
};

const cells = meiosisSetup<State>({ app });

const element = document.getElementById('app') as HTMLElement;
cells.map((cell) => {
  preact.render(app.view(cell), element);
});

// helpers/setup/views/lit-html/src/index.js
import meiosis from "../../../dist/meiosis-setup";
import { html, render } from "lit-html";

const App = ({ state, update, actions }) => html`
  <div>
    <div>Counter: ${state.counter}</div>
    <div>Greeting: ${state.greeting}</div>
    <div>
      <button @click=${() => actions.increment()}>Increment</button>
    </div>
    <div>
      <button @click=${() => update(state => ({ ...state, greeting: "Hello" }))}>Say Hello</button>
    </div>
  </div>
`;

const { states, update, actions } = meiosis.functionPatches.setup({
  stream: meiosis.simpleStream,
  app: {
    initial: { counter: 0 },
    Actions: update => ({
      increment: () => update(state => ({ ...state, counter: state.counter + 1 }))
    })
  }
});

const element = document.getElementById("app");
states.map(state => render(App({ state, update, actions }), element));
